<?php

namespace Database\Seeders;

use App\Models\UnidadNegocio;
use Illuminate\Database\Seeder;

class UnidadNegocioSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $names = [
            'Mauro',
            'Gonzalez Casado, Camila',
            'Paula Suarez',
            'Aguilar Laura Soledad',
            'Bonfanti, Edith',
            'Bonazza Daniel Oscar',
            'Mariana de Mendieta',
            'Miranda Sergio',
            'Gutierrez, Juliana',
            'Andrea Baigorria',
            'Bernardi Bosco Nicolás Alejandro',
            'Larrosa, Carolina',
            'Leandro Morán',
            'Patricio Baigorria',
            'Romina Bottinelli',
            'Stella Espindola',
            'Tabares Vanina Alejandra',
            'Chiappero, Jose Maria',
            'Loro, Luis',
            'Morra, Vanina',
            'Romagnoli, Santiago',
            'Marino, Miguel',
            'Villella, Matías',
            'Sapia, Florencia',
            'Tomic, Leandro',
            'Gonzalez María Belén',
            'Kunte, Ana',
            'Bustos, Camila',
            'Falessi, Belén',
            'Manuel Agnello',
            'Martinez, María Cecilia',
            'Nombre',
            'Davalos, Micaela Victoria',
            'Farias, Agustina Carolina',
            'Rios Bruno Ricardo',
            'Gretel',
            'Eliana Vaccaro',
            'Guillermo Guanco',
            'Siniestros Patrimoniales',
        ];
        $emails = [
            'mm@gmail.com',
            'camila.gonzalez-casado@metlife.com.ar',
            'psuarez@lifeseguros.com.ar)',
            'laguilar@sancorseguros.com',
            'ebonfanti@sancorseguros.com',
            'dbonazza@sancorseguros.com',
            'mdemendieta@sancorseguros.com',
            'SMiranda@sancorseguros.com',
            'JGutierrez@sancorseguros.com',
            'ABaigorria@lifeseguros.com.ar',
            'nbernardi@sancorseguros.com',
            'CLarrosa@sancorseguros.com',
            '',
            '',
            '',
            'sespindola.externo@lifeseguros.com.ar',
            'vtabares@sancorseguros.com',
            'JChiappero@sancorseguros.com',
            'lloro@sancorseguros.com',
            'vmorra@sancorseguros.com',
            'sromagnoli@sancorseguros.com',
            'MMarino@sancorseguros.com',
            'mvillella@sancorseguros.com',
            'fsapia@prevencionart.com.ar',
            'ltomic@sancorseguros.com',
            'mgonzalez@prevencionart.com.ar',
            'AKunte@sancorseguros.com',
            'cabustos@ext.sancorseguros.com',
            'BFalessi@sancorseguros.com',
            'MAgnello@sancorseguros.com',
            'marimartinez@ext.sancorseguros.com',
            'email@gmail.com',
            'midavalos@prevencionart.com.ar',
            'acfarias@sancorseguros.com',
            'brios@prevencionart.com.ar',
            'siniestros.patrimoniales@lifeseguros.com.ar',
            'siniestros.patrimoniales@lifeseguros.com.ar',
            'siniestros.patrimoniales@lifeseguros.com.ar',
            'siniestros.patrimoniales@lifeseguros.com.ar',
        ];
        $business_untis = [
            'mauro',
            'Capital Federal',
            'Capital Federal',
            'Concordia',
            'Parana',
            'Casa Central',
            'General Roca',
            'General Roca',
            'Bahia Blanca',
            'Capital Federal',
            'Capital Federal',
            'Capital Federal',
            'Capital Federal',
            'Capital Federal',
            'Capital Federal',
            'Capital Federal',
            'Capital Federal',
            'Casa Central',
            'Casa Central',
            'Casa Central',
            'Casa Central',
            'Cordoba',
            'Cordoba',
            'Mar del Plata',
            'Mar del Plata',
            'Mendoza',
            'Parana',
            'Rosario',
            'Rosario',
            'Rosario',
            'Rosario',
            'Gestor',
            'Buenos Aires',
            '',
            'Gral. Roca',
            'Life Seguros',
            'Life Seguros',
            'Life Seguros',
            'Life Seguros',
        ];
        $addresses = [
            'afdmaskdf',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            'UN',
            '',
            '',
            '',
            'Tte. Gral. Juan Domingo Perón 646, C1038AAN CABA',
            'Tte. Gral. Juan Domingo Perón 646, C1038AAN CABA',
            'Tte. Gral. Juan Domingo Perón 646, C1038AAN CABA',
            'Tte. Gral. Juan Domingo Perón 646, C1038AAN CABA',
        ];
        $phones = [
            'afmasdlfdsf',
            '11-3056-7865',
            '',
            '',
            '',
            '',
            '0298-4434745 Int. 24512',
            '+54 (0298) 4434745 Int 24522',
            '',
            '',
            '',
            '+54 (11) 4120 3300 Int.20159',
            '',
            '',
            '',
            '',
            '1154240367',
            '3493 428500 Int.53176',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '+54 (261) 4259999. Int. 25142',
            '',
            '',
            '',
            '+54 9 3413 08-6976',
            '54 9 3413 65-2760',
            'Telefono',
            '54 (11) 4120-3300. Int. 24793',
            '',
            '0298-4434745 Int.',
            '',
            '',
            '',
            '',
        ];
        $num = 1;
        for ($i=0; $i < count($names); $i++) { 
            UnidadNegocio::create([
                'num'                   => $num,
                'nombre'                => $names[$i],
                'email'                 => $emails[$i],
                'domicilio'             => $addresses[$i],
                'telefono_conmutador'   => $phones[$i],
                'aseguradora_id'        => 1,
                'user_id'               => 1,
            ]);
            $num++;
        }
    }
}
